<?php

namespace Database\Seeders;

use App\Models\Product;
use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run() {
        Schema::disableForeignKeyConstraints();
        Product::truncate();

        Product::insert([
            // 1
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 0,
		        'product_name' => "Classic Blue Printed Casual Shirt by RICHMAN",
		        'product_url' => Str::slug('Classic Blue Printed Casual Shirt by RICHMAN'),
		        'brand_id' => 1,
                'selected_categories' => ["1", "2"],
                'short_description' => "<ul><li>Material composition: 100% Cotton</li><li>Style: casual</li><li>Care: wash with similar color, wash, do not bleach, and do not tumble dry.</li><li>Iron: iron at maximum of 110ºc/230ºf.</li><li><b>product color may slightly vary due to photographic lighting.</b></li><li>Take good care of it.</li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 2139.90,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Classic Blue Printed Casual Shirt by RICHMAN",
                'search_keywords' => "Classic Blue Printed Casual Shirt by RICHMAN",
                'meta_description' => "Classic Blue Printed Casual Shirt by RICHMAN",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug('Classic Blue Printed Casual Shirt by RICHMAN'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 2
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 0,
		        'product_name' => "Men’s White Color Black Striped Polo Shirt by Richman",
		        'product_url' => Str::slug('Men’s White Color Black Striped Polo Shirt by Richman'),
		        'brand_id' => 1,
                'selected_categories' => ["1", "6", "13"],
                'short_description' => "<ul><li>Material composition: 95% Polyester &amp; 5% Spandex</li><li>Style: casual</li><li>Care: wash with similar color, wash, do not bleach, and do not tumble dry.</li><li>Iron: iron at maximum of 110ºc/230ºf.</li><li><b>product color may slightly vary due to photographic lighting.</b></li><li>Take good care of it.</li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 1611.75,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s White Color Black Striped Polo Shirt by Richman",
                'search_keywords' => "Men’s White Color Black Striped Polo Shirt by Richman",
                'meta_description' => "Men’s White Color Black Striped Polo Shirt by Richman",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug('Men’s White Color Black Striped Polo Shirt by Richman'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 3
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 0,
		        'product_name' => "Men’s Ash Color Cotton Full Sleeve Slim Fit Formal Shirt",
		        'product_url' => Str::slug('Men’s Ash Color Cotton Full Sleeve Slim Fit Formal Shirt'),
		        'brand_id' => 1,
                'selected_categories' => ["1", "2", "3"],
                'short_description' => "<ul><li>95% Cotton &amp; 5% Elastin</li><li>Slim-Fit</li><li>Available in sizes S to XXL</li><li>Ash Color</li><li>Suitable for all occasions.</li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 2921.10,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Ash Color Cotton Full Sleeve Slim Fit Formal Shirt",
                'search_keywords' => "Men’s Ash Color Cotton Full Sleeve Slim Fit Formal Shirt",
                'meta_description' => "Men’s Ash Color Cotton Full Sleeve Slim Fit Formal Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Men’s Ash Color Cotton Full Sleeve Slim Fit Formal Shirt"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 4
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Premium Black Formal Pant by RICHMAN",
		        'product_url' => Str::slug('Premium Black Formal Pant by RICHMAN'),
		        'brand_id' => 1,
                'selected_categories' => ["1", "7"],
                'short_description' => "<p>Colour: Black<br>Fabric: Blended<br>Care: Dry Clean Only.<br>The model is wearing a size 32</p>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 2783.55,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Premium Black Formal Pant by RICHMAN",
                'search_keywords' => "Premium Black Formal Pant by RICHMAN",
                'meta_description' => "Premium Black Formal Pant by RICHMAN",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug('Premium Black Formal Pant by RICHMAN'),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 5
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Richman Men’s White Striped Half Sleeve Round Neck T-Shirt",
		        'product_url' => Str::slug('Richman Men’s White Striped Half Sleeve Round Neck T-Shirt'),
		        'brand_id' => 1,
                'selected_categories' => ["1", "6"],
                'short_description' => "<ul><li>Fabrics: 100% Cotton</li><li>Short sleeves</li><li>Available in sizes S to XXL</li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 928.00,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Richman Men’s White Striped Half Sleeve Round Neck T-Shirt",
                'search_keywords' => "Richman Men’s White Striped Half Sleeve Round Neck T-Shirt",
                'meta_description' => "Richman Men’s White Striped Half Sleeve Round Neck T-Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Richman Men’s White Striped Half Sleeve Round Neck T-Shirt"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 6
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Men’s Sky Color Full Sleeve Cotton Regular Fit Formal Shirt",
		        'product_url' => Str::slug('Men’s Sky Color Full Sleeve Cotton Regular Fit Formal Shirt'),
		        'brand_id' => 1,
                'selected_categories' => ["2", "3"],
                'short_description' => "<ul><li>100% Cotton</li><li>Regular Fit</li><li>Available in sizes S to XXL</li><li>Sky Color</li><li>Suitable for all occasions.</li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 3409.00,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Sky Color Full Sleeve Cotton Regular Fit Formal Shirt",
                'search_keywords' => "Men’s Sky Color Full Sleeve Cotton Regular Fit Formal Shirt",
                'meta_description' => "Men’s Sky Color Full Sleeve Cotton Regular Fit Formal Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Men’s Sky Color Full Sleeve Cotton Regular Fit Formal Shirt"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 7
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Men’s Black Color Full Sleeve Cotton Regular Fit Formal Shirt",
		        'product_url' => Str::slug('Men’s Black Color Full Sleeve Cotton Regular Fit Formal Shirt'),
		        'brand_id' => 1,
                'selected_categories' => ["2", "3"],
                'short_description' => "<ul><li>100% Cotton</li><li>Regular Fit</li><li>Available in sizes S to XXL</li><li>Black Color</li><li>Suitable for all occasions.</li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 2588.00,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Black Color Full Sleeve Cotton Regular Fit Formal Shirt",
                'search_keywords' => "Men’s Black Color Full Sleeve Cotton Regular Fit Formal Shirt",
                'meta_description' => "Men’s Black Color Full Sleeve Cotton Regular Fit Formal Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Men’s Black Color Full Sleeve Cotton Regular Fit Formal Shirt"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 8
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Premium Black Check Blazer by RICHMAN",
		        'product_url' => Str::slug('Premium Black Check Blazer by RICHMAN'),
		        'brand_id' => 1,
                'selected_categories' => ["1", "2", "5"],
                'short_description' => "<ul><li>Dry wash only</li><li>Do not Bleach, and Do not tumble dry.</li><li>Iron at a maximum of 110ºc/230ºf.</li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 6827.00,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Premium Black Check Blazer by RICHMAN",
                'search_keywords' => "Premium Black Check Blazer by RICHMAN",
                'meta_description' => "Premium Black Check Blazer by RICHMAN",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Premium Black Check Blazer by RICHMAN"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 9
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Men’s Khaki Color Slim-fit Blazer by Richman",
		        'product_url' => Str::slug('Men’s Khaki Color Slim-fit Blazer by Richman'),
		        'brand_id' => 1,
                'selected_categories' => ["2", "5"],
                'short_description' => "<ul><li>Dry wash only</li><li>Do not Bleach, and Do not tumble dry.</li><li>Iron at a maximum of 110ºc/230ºf.</li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 7472.09,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Khaki Color Slim-fit Blazer by Richman",
                'search_keywords' => "Men’s Khaki Color Slim-fit Blazer by Richman",
                'meta_description' => "Men’s Khaki Color Slim-fit Blazer by Richman",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Men’s Khaki Color Slim-fit Blazer by Richman"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 10
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Men’s Blue Color Slim-fit Blazer by Richman",
		        'product_url' => Str::slug('Men’s Blue Color Slim-fit Blazer by Richman'),
		        'brand_id' => 1,
                'selected_categories' => ["2", "5"],
                'short_description' => "<ul><li>Dry wash only</li><li>Do not Bleach, and Do not tumble dry.</li><li>Iron at a maximum of 110ºc/230ºf.</li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 7472.09,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Blue Color Slim-fit Blazer by Richman",
                'search_keywords' => "Men’s Blue Color Slim-fit Blazer by Richman",
                'meta_description' => "Men’s Blue Color Slim-fit Blazer by Richman",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Men’s Blue Color Slim-fit Blazer by Richman"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 11
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Richman Men’s Olive Color Half Sleeve Round Neck T-Shirt",
		        'product_url' => Str::slug('Richman Men’s Olive Color Half Sleeve Round Neck T-Shirt'),
		        'brand_id' => 1,
                'selected_categories' => ["1", "6"],
                'short_description' => "<ul><li>Fabrics: 95% Cotton &amp; 5% Spandex</li><li>Short sleeves</li><li>Available in sizes S to XXL</li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 1025.85,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Richman Men’s Olive Color Half Sleeve Round Neck T-Shirt",
                'search_keywords' => "Richman Men’s Olive Color Half Sleeve Round Neck T-Shirt",
                'meta_description' => "Richman Men’s Olive Color Half Sleeve Round Neck T-Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Richman Men’s Olive Color Half Sleeve Round Neck T-Shirt"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 12
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Coconut Tree Theme comfy T-shirt by RICHMAN",
		        'product_url' => Str::slug('Coconut Tree Theme comfy T-shirt by RICHMAN'),
		        'brand_id' => 1,
                'selected_categories' => ["1", "6"],
                'short_description' => "<ul><li>Fabrics: 95% Cotton &amp; 5% Spandex</li><li>Short sleeves</li><li>Available in sizes S to XXL</li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 967.00,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Coconut Tree Theme comfy T-shirt by RICHMAN",
                'search_keywords' => "Coconut Tree Theme comfy T-shirt by RICHMAN",
                'meta_description' => "Coconut Tree Theme comfy T-shirt by RICHMAN",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Coconut Tree Theme comfy T-shirt by RICHMAN"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 13
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Richman Olive Color Solid Half Sleeve Polo Shirt",
		        'product_url' => Str::slug('Richman Olive Color Solid Half Sleeve Polo Shirt'),
		        'brand_id' => 1,
                'selected_categories' => ["13"],
                'short_description' => "<ul><li>Fabrics: 95% Cotton &amp; 5% Spandex</li><li>Short sleeves</li><li>Available in sizes S to XXL</li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 1416.45,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Richman Olive Color Solid Half Sleeve Polo Shirt",
                'search_keywords' => "Richman Olive Color Solid Half Sleeve Polo Shirt",
                'meta_description' => "Richman Olive Color Solid Half Sleeve Polo Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Richman Olive Color Solid Half Sleeve Polo Shirt"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 14
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "Richman Coffee Color Printed Half Sleeve Polo Shirtt",
		        'product_url' => Str::slug('Richman Coffee Color Printed Half Sleeve Polo Shirt'),
		        'brand_id' => 1,
                'selected_categories' => ["1", "13"],
                'short_description' => "<ul><li>Fabrics: 95% Cotton &amp; 5% Spandex</li><li>Short sleeves</li><li>Available in sizes S to XXL</li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 1318.80,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Richman Coffee Color Printed Half Sleeve Polo Shirt",
                'search_keywords' => "Richman Coffee Color Printed Half Sleeve Polo Shirt",
                'meta_description' => "Richman Coffee Color Printed Half Sleeve Polo Shirt",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Richman Coffee Color Printed Half Sleeve Polo Shirt"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 15
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "RPremium Black Color Denim",
		        'product_url' => Str::slug('Premium Black Color Denim'),
		        'brand_id' => 1,
                'selected_categories' => ["7", "8"],
                'short_description' => "<ul><li><p>Slim-fit jeans. Five pockets. Faded effect. Zip fly and button fastening on the front.</p></li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 2392.95,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Premium Black Color Denim",
                'search_keywords' => "Premium Black Color Denim",
                'meta_description' => "Premium Black Color Denim",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Premium Black Color Denim"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
            // 16
        	[
        		'sku' => 'A584786',
		        'is_top_product' => 1,
		        'view_count' => 4,
		        'product_name' => "RMen’s Dark Blue color Denim Pant by Richman",
		        'product_url' => Str::slug('Men’s Dark Blue color Denim Pant by Richman'),
		        'brand_id' => 1,
                'selected_categories' => ["7", "8"],
                'short_description' => "<ul><li><p>Slim-fit jeans. Five pockets. Faded effect. Zip fly and button fastening on the front.</p></li></ul>",
                'description' => "",
                'specification' => "",
                'warranty_information' => null,
                'image' => null,
                'cost' => null,
                'sales_price' => 2724.75,
                'call_for_price' => null,
                'is_upcoming' => 0,
                'is_tba' => 0,
                'is_pre_order' => 0,
                'is_in_stock' => 1,
                'low_stock' => 10,
                'stock' => 80,
                'width' => null,
                'height' => null,
                'depth' => null,
                'weight' => null,
                'page_title' => "Men’s Dark Blue color Denim Pant by Richman",
                'search_keywords' => "Men’s Dark Blue color Denim Pant by Richman",
                'meta_description' => "Men’s Dark Blue color Denim Pant by Richman",
                'schema_tag' => null,
                'video_url' => null,
                'creator' => null,
                'slug' => Str::slug("Men’s Dark Blue color Denim Pant by Richman"),
                'status' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
		    ],
        ]);
    }
}
